### ISSUE TITLE
Consider adopting a well-known license?

### ISSUE THREAD

**Issue by jprjr** [bbbradsmith/nsfplay#29]
The current license text in the readme isn't one of the "standard" licenses, I thought I'd suggest adopting one of the well-known licenses - [here's a list of common ones](https://choosealicense.com/licenses/), and [a list of even more](https://choosealicense.com/appendix/)

I think the [BSD Zero Clause](https://choosealicense.com/licenses/0bsd/) license is closest to what's currently in the readme file, or maybe the [Unlicense](https://choosealicense.com/licenses/unlicense/). If you want attribution, [MIT](https://choosealicense.com/licenses/mit/) is also pretty close.

The main benefit is making decisions easier for other projects - like certain Linux distros get picky about the licenses attached to software. If they can't quickly classify it, they probably just won't package it.

**Comment by bbbradsmith** [comment]
I'm aware of common licenses, and do not wish to use them at this time.
