### ISSUE TITLE
Playback speed issues with stereo mode. (v2.5 beta)

### ISSUE THREAD

**Issue by B00daW** [bbbradsmith/nsfplay#40]
Brad,

I am using Wine v5.7, pulseaudio and a Realtek audio chipset with Linux v5.6.10 kernel.  If "stereo mode" is enabled in v2.5 beta of NSFPlay then the audio file is played back at max speed.  If it is disabled, it plays normally.

Oh!  And stereo mode seems to be the default configuration on start-up.  Until resolved, a dirty fix could be to not include it as a default option.

Please investigate.  Thanks!

**Comment by bbbradsmith** [comment]
Stereo mode has to stay as the default option, mono causes problems for a lot of hardware (esp. people with surround sound setup).

As for the max speed issue, could you describe that in more detail? Is the pitch different? Is it exactly 2x as fast?

**Comment by B00daW** [comment]
https://cdn.discordapp.com/attachments/706602783154896988/706602844824010793/1942.mp3

So this is very bizarre.  First bit of recording is with stereo mode off on 1942.  Second bit is with stereo mode on.  However, Audacity is recording my output very slowly, but when I hear it from NSFPlay it's very fast.  May have to record directly from the headphones jack onto something else if you can't figure it out from this. :/

**Comment by bbbradsmith** [comment]
What exactly are you recording? The loopback from your audio drivers?

What happens when you save as WAV? (The red folder icon on NSFPlay's panel.) Is the audio still corrupted there, or is this only when outputting to audio drivers?

**Comment by B00daW** [comment]
https://cdn.discordapp.com/attachments/706602783154896988/706674611257081966/1942b.mp3

OK.  Here is the audio recorded from the Linux laptop to another source.

Weird how before it was consistently working when stereo mode was turned off.  Now it seems that it's always playing fast like this.  Am I doing something wrong?

**Comment by bbbradsmith** [comment]
What happens when you export as WAV?

**Comment by B00daW** [comment]
https://cdn.discordapp.com/attachments/706602783154896988/706852316942434344/1942wav.mp3

Exporting seems to WAV has no issues.

**Comment by bbbradsmith** [comment]
Hmm, that MP3 is mono. Does the WAV export have any problem in stereo? (If WAV export works, that narrows down the possibilities a lot for what can be going wrong.)

**Comment by B00daW** [comment]
https://cdn.discordapp.com/attachments/706602783154896988/707218223275442286/3dbattleswav2.mp3

This is 3D Battles of World Runner in stereo mode.  Both square channels are used in this one so it should output a stereo file.  I don't notice much of a difference.

**Comment by bbbradsmith** [comment]
Thanks, that rules out a lot of possibilities.

**Comment by bbbradsmith** [comment]
With no other reports of this issue, I will close it for now. Please re-open if it resurfaces.
