### ISSUE TITLE
Unable to play music when files are opened directly from Windows explorer

### ISSUE THREAD

**Issue by KiON-GiON** [bbbradsmith/nsfplay#47]
Hi,
A few hours ago I updated my NSFPlay copy, but whenever I open files from the Windows explorer, NSFPlay doesn't play anything and it crashes. (I've NSFPlay as the default player)
I deleted all the settings, but that doesn't solved my issue.
But when I open files using NSFP's file explorer, all the NSFs play just fine.
I've re-downloaded the stable version to confirm if it works, and indeed it does.
I'm sorry, I don't have more details. The logs that Windows leaves in the event viewer didn't help much either.

**Comment by bbbradsmith** [comment]
Hmm, that's one I'm not able to duplicate. Does drag & drop work?

If you open regedit and search for "nsfplay.exe" what "command" keys do you find? A normal command should look like:

```
"C:\...\nsfplay.exe" "%1"
```

**Comment by KiON-GiON** [comment]
Yeah, drag & drop works just fine.
The regedit key is looking exactly as you said.
And, this is the event viewer's log:

Log Name:Application
Source:        Application Error
Date:         31-10-2020 15:50:32
Event ID:1000
Task Category:(100)
Level:         Error
Keywords:Classic
User:       N/A
Computer:        
Description:
Faulting application name: nsfplay.exe, version: 2.3.0.0, time stamp: 0x5f99ee84
Faulting module name: in_yansf.dll, version: 0.0.0.0, time stamp: 0x5f99ee59
Exception code: 0xc0000005
Fault offset: 0x00018447
Faulting process ID: 0x6b4
Faulting application start time: 0x01d6afb6b4e00834
Faulting application path: C:\Users\ \Desktop\VGM\FCNES\nsfplay\nsfplay.exe
Faulting module path: C:\Users\ \Desktop\VGM\FCNES\nsfplay\plugins\in_yansf.dll
Report ID: cd8ba361-12e5-4b5e-9c92-88a6ca528eb2
Faulting package full name: 
Faulting package-relative application ID: 
XML de evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-31T18:50:32.268155600Z" />
    <EventRecordID>43113</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-BN6SV6C</Computer>
    <Security />
  </System>
  <EventData>
    <Data>nsfplay.exe</Data>
    <Data>2.3.0.0</Data>
    <Data>5f99ee84</Data>
    <Data>in_yansf.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>5f99ee59</Data>
    <Data>c0000005</Data>
    <Data>00018447</Data>
    <Data>6b4</Data>
    <Data>01d6afb6b4e00834</Data>
    <Data>C:\Users\ \Desktop\VGM\FCNES\nsfplay\nsfplay.exe</Data>
    <Data>C:\Users\ \Desktop\VGM\FCNES\nsfplay\plugins\in_yansf.dll</Data>
    <Data>cd8ba361-12e5-4b5e-9c92-88a6ca528eb2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by KiON-GiON** [comment]
Yeah, drag & drop works just fine, and the regedit key is looking as you descrived. Here's the log:

Log Name:Application
Source:        Application Error
Date:         31-10-2020 15:50:32
Event ID:1000
Task Category:(100)
Level:         Error
Keywords:Classic
User:       N/A
Computer:        [removed]
Description:
Faulting application name: nsfplay.exe, version: 2.3.0.0, time stamp: 0x5f99ee84
Faulting module name: in_yansf.dll, version: 0.0.0.0, time stamp: 0x5f99ee59
Exception code: 0xc0000005
Fault offset: 0x00018447
Faulting process ID: 0x6b4
Faulting application start time: 0x01d6afb6b4e00834
Faulting application path: C:\Users\...\Desktop\VGM\FCNES\nsfplay\nsfplay.exe
Faulting module path: C:\Users\...\Desktop\VGM\FCNES\nsfplay\plugins\in_yansf.dll
Report ID: cd8ba361-12e5-4b5e-9c92-88a6ca528eb2
Faulting package full name: 
Faulting package-relative application ID: 
XML de evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-31T18:50:32.268155600Z" />
    <EventRecordID>43113</EventRecordID>
    <Channel>Application</Channel>
    <Security />
  </System>
  <EventData>
    <Data>nsfplay.exe</Data>
    <Data>2.3.0.0</Data>
    <Data>5f99ee84</Data>
    <Data>in_yansf.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>5f99ee59</Data>
    <Data>c0000005</Data>
    <Data>00018447</Data>
    <Data>6b4</Data>
    <Data>01d6afb6b4e00834</Data>
    <Data>C:\Users\...\Desktop\VGM\FCNES\nsfplay\nsfplay.exe</Data>
    <Data>C:\Users\...\Desktop\VGM\FCNES\nsfplay\plugins\in_yansf.dll</Data>
    <Data>cd8ba361-12e5-4b5e-9c92-88a6ca528eb2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by bbbradsmith** [comment]
Will close this for the time being, but can revisit it if it resurfaces.
