### ISSUE TITLE
Add half-linear mixer on APU1?

### ISSUE THREAD

**Issue by Yave-Yu** [bbbradsmith/nsfplay#57]
Half-Linear sounds like real NES(Famicom) and Nestopia's effect (when two 75% square wave plays).

**Comment by bbbradsmith** [comment]
I would need an explanation of what this means.

Can you take a recording of a real NES or Famicom that demonstrates it?

**Comment by Yave-Yu** [comment]
Two loud 75% square wave plays~
[Example.zip](https://github.com/bbbradsmith/nsfplay/files/5834675/Example.zip)
0: Linear, sounds clear.
1: "Half-Linear", sounds a little blurry but still clear.
2: Non-Linear, sounds blurry.

Example1's effect sounds like between Linear and Non-Linear, so I call it "Half-Linear" (I don't know how exactly call it). Very shame only Nestopia has it, so I hope you can implement this into NSFPlay.

**Comment by bbbradsmith** [comment]
I don't see an option for this in Nestopia.

What is the actual effect that is being described here?

**Comment by Yave-Yu** [comment]
Yeah, Nestopia didn't give any audio mixer option, it has native effect like Example1.
I'm using earphone to hear, so they are result:
> 0: Linear, sounds clear.
> 1: "Half-Linear", sounds a little blurry but still clear.
> 2: Non-Linear, sounds blurry.
However I don't know how to exactly and accuracy describe it...

**Comment by bbbradsmith** [comment]
Well, I don't have anything I can act on here then. I will close this pending further information.

NSFPlay already has an option for linear (inaccurate) and non-linear (more accurate to NES) mixing of both APU channels.

If that's not what you are looking for then you will have to come back with information on an algorithm, or at least a recording of an NSF example from a real NES or Famicom (not an emiulator) that you can demonstrate is different from NSFPlay.
