### ISSUE TITLE
NSFPlay plays Super Pang II failed

### ISSUE THREAD

**Issue by Yave-Yu** [bbbradsmith/nsfplay#58]
No sound output...

**Comment by bbbradsmith** [comment]
Linking to an NSF so I can look at this later: https://mail.ninjaproxy.com/music/nintendo-nes-nsf/super-pang-2

**Comment by bbbradsmith** [comment]
This NSF rip makes strange out of bounds writes in its INIT routines, specifically to $4100 where NSFPlay had placed its own internal playback stub code, breaking NSFPlay.

The NSF should not write to this area, but I will try to add a write protect to it to prevent this problem.

**Comment by bbbradsmith** [comment]
Fixed with: b11dc81c741957e4743664102fc20094c2b756df
