### ISSUE TITLE
Would it be possible to add a "render all channels separately" feature?

### ISSUE THREAD

**Issue by etoubleh** [bbbradsmith/nsfplay#72]
Basically what the title says. Would it be possible to add a feature that automatically renders all channels separately for a file, like what OpenMPT has?

**Comment by bbbradsmith** [comment]
That's possible, yes. It's been requested before and it's on the roadmap for version 3.

If you need to automate it right now, you might be able to do it with several copies of the configuration with different channel volumes and a batch file that does a command line export with each of those configuration.
