### ISSUE TITLE
Request: Batch WAV export before v3?

### ISSUE THREAD

**Issue by toasterberry** [bbbradsmith/nsfplay#74]
Would it be possible to see a batch export feature sometime before v3? I'd like it to export every track in an NSF/NSFE file to a directory, titling the tracks automatically, with a couple button presses. I downloaded the source and tried to implement it myself, but I couldn't get any changes to work at all, probably because I have no idea what I'm doing.

I think this would be a popular feature, I'm shocked it hasn't been requested already (unless I missed it). I hope to see it implemented sometime before v3.

**Comment by bbbradsmith** [comment]
I'll add it to the roadmap, but I can't offer any timeline.
