### ISSUE TITLE
Odd window size

### ISSUE THREAD

**Issue by badgertapes** [bbbradsmith/nsfplay#78]
NSFPlay is currently displaying a larger window size with a different font and bigger buttons. Not sure why this is happening. Only happened after I gave my PC a reinstall. Redownloading program did not fix.
![2](https://github.com/bbbradsmith/nsfplay/assets/17790865/921f0d47-667f-4c90-bd09-0cb4d230c5d4)
Would definitely like to know if this issue is known or what causes it. Thank you.

**Comment by bbbradsmith** [comment]
Not sure, maybe your PC is now missing MS Sans Serif or it got replaced by some high-DPI enlarged version of the font? In your Windows Display settings do you have "Make text bigger" or "Make everything bigger" enabled?

**Comment by badgertapes** [comment]
Everything is set to 100% size. Font here looks like Fixedsys rather than MS Sans Serif. Odd

**Comment by badgertapes** [comment]
can now confirm this is a windows-related issue and not an nsfplay bug. specific version of ms sans serif was missing.

**Comment by badgertapes** [comment]
can now confirm this is a windows-related issue and not an nsfplay bug. specific version of ms sans serif was missing.

**Comment by bbbradsmith** [comment]
Thanks for following it up.
